// Generated by CoffeeScript 1.10.0
var assert, expect, should;

expect = chai.expect;

assert = chai.assert;

should = chai.should();

describe("Hand tests", function() {
  var dealerHand, deck, playerHand;
  deck = null;
  playerHand = null;
  dealerHand = null;
  beforeEach(function() {
    deck = new Deck();
    playerHand = deck.dealPlayer();
    return dealerHand = deck.dealDealer();
  });
  it("should have a hit, hasAce, and minScore methods", function() {
    expect(playerHand.hit).to.be.a('function');
    assert.isFunction(playerHand.hasAce);
    return playerHand.minScore.should.be.a('function');
  });
  it("playerHand should be an instanceof Hand", function() {
    return expect(playerHand).to.be.an.instanceOf(Hand);
  });
  it("should have four cards after hitting", function() {
    playerHand.hit();
    playerHand.hit();
    return assert.strictEqual(playerHand.length, 4);
  });
  it("should return false for hasAce", function() {
    playerHand.add(new Card({
      rank: 5,
      suit: 3
    }));
    return playerHand.hasAce().should.equal(false);
  });
  return it("should return true for hasAce", function() {
    playerHand.add(new Card({
      rank: 1,
      suit: 3
    }));
    expect(playerHand.hasAce()).to.equal(true);
    return assert.isTrue(playerHand.hasAce());
  });
});
