// Generated by CoffeeScript 1.10.0
var assert, expect;

assert = chai.assert;

expect = chai.expect;

describe("deck constructor", function() {
  return it("should create a card collection", function() {
    var collection;
    collection = new Deck();
    return assert.strictEqual(collection.length, 52);
  });
});

describe("card constructor", function() {
  var card;
  card = null;
  beforeEach(function() {
    return card = new Card({
      rank: 5,
      suit: 2
    });
  });
  it("should have a rank", function() {
    return expect(card.attributes).to.have.property('rank');
  });
  it("should have a value of 5", function() {
    return expect(card.attributes.rank).to.equal(5);
  });
  return it("should have a flip method", function() {
    return expect(card.flip).to.be.an('function');
  });
});
